-- MySQL Script generated by MySQL Workbench
-- 01/03/16 16:06:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hurryup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hurryup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hurryup` ;
USE `hurryup` ;

-- -----------------------------------------------------
-- Table `hurryup`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hurryup`.`member` (
  `id` VARCHAR(50) NOT NULL,
  `pw` VARCHAR(100) NOT NULL,
  `credit` INT(11) NOT NULL DEFAULT '0',
  `latitude` DOUBLE NOT NULL DEFAULT '0',
  `longitude` DOUBLE NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hurryup`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hurryup`.`meeting` (
  `m_id` INT(11) NOT NULL AUTO_INCREMENT,
  `m_title` VARCHAR(45) NOT NULL,
  `m_location` VARCHAR(100) NOT NULL,
  `m_latitude` DOUBLE NOT NULL,
  `m_longitude` DOUBLE NOT NULL,
  `m_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `m_host` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`m_id`),
  INDEX `meet_host_idx` (`m_host` ASC),
  CONSTRAINT `meet_host`
    FOREIGN KEY (`m_host`)
    REFERENCES `hurryup`.`member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hurryup`.`meeting_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hurryup`.`meeting_members` (
  `meeting_id` INT(11) NOT NULL,
  `meeting_member` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`meeting_id`, `meeting_member`),
  INDEX `meeting_member_for_idx` (`meeting_member` ASC),
  CONSTRAINT `meeting_id_for`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `hurryup`.`meeting` (`m_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `meeting_member_for`
    FOREIGN KEY (`meeting_member`)
    REFERENCES `hurryup`.`member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
